"""
Smart Campus Analytics - Excel Report Generator
Produces a multi-sheet, color-coded analytics workbook.
"""

import pandas as pd
import numpy as np
from openpyxl import Workbook
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.chart.series import DataPoint
from openpyxl.formatting.rule import ColorScaleRule, DataBarRule
import os

# ── Color palette ─────────────────────────────────────────────────────────────
C = {
    'dark_blue':   '1F4E79', 'mid_blue':  '2E75B6', 'light_blue': 'DEEAF1',
    'green':       '27AE60', 'light_green':'D5F5E3',
    'red':         'E74C3C', 'light_red': 'FADBD8',
    'orange':      'E67E22', 'light_orange':'FDEBD0',
    'yellow':      'F4D03F', 'light_yellow':'FEF9E7',
    'white':       'FFFFFF', 'header_row':'F2F2F2',
    'risk_critical':'E74C3C','risk_high':  'E67E22',
    'risk_moderate':'F4D03F','risk_low':   '27AE60',
}

RISK_BG = {'Critical': C['light_red'], 'High': C['light_orange'],
           'Moderate': C['light_yellow'], 'Low': C['light_green']}
GRADE_BG = {'A': 'D5F5E3', 'B': 'D6EAF8', 'C': 'FEF9E7',
             'D': 'FDEBD0', 'F': 'FADBD8'}

def _font(bold=False, size=11, color='000000', italic=False):
    return Font(name='Arial', bold=bold, size=size, color=color, italic=italic)

def _fill(hex_color):
    return PatternFill('solid', fgColor=hex_color)

def _align(h='left', v='center', wrap=False):
    return Alignment(horizontal=h, vertical=v, wrap_text=wrap)

def _border(style='thin', color='CCCCCC'):
    s = Side(style=style, color=color)
    return Border(left=s, right=s, top=s, bottom=s)

def _header_style(ws, row, bg=None, font_color='FFFFFF', bold=True, size=11):
    bg = bg or C['dark_blue']
    for cell in ws[row]:
        if cell.value is not None:
            cell.font      = _font(bold=bold, size=size, color=font_color)
            cell.fill      = _fill(bg)
            cell.alignment = _align('center')
            cell.border    = _border()

def _col_width(ws, col_letter, width):
    ws.column_dimensions[col_letter].width = width

def _freeze(ws, cell='A2'):
    ws.freeze_panes = ws[cell]


# ── Sheet 1: Dashboard ────────────────────────────────────────────────────────

def _build_dashboard(ws, df):
    ws.sheet_properties.tabColor = C['dark_blue']
    ws.column_dimensions['A'].width = 2

    # Title block
    ws.merge_cells('B2:L3')
    title = ws['B2']
    title.value     = 'AI-Powered Smart Campus Analytics — Executive Dashboard'
    title.font      = _font(bold=True, size=18, color='FFFFFF')
    title.fill      = _fill(C['dark_blue'])
    title.alignment = _align('center')

    ws.merge_cells('B4:L4')
    sub = ws['B4']
    sub.value     = f'Student Cohort: {len(df)} CS Students  |  Generated by Smart Campus Analytics System'
    sub.font      = _font(size=10, color=C['mid_blue'], italic=True)
    sub.alignment = _align('center')

    # KPI boxes row 6–8
    kpis = [
        ('B', 'TOTAL STUDENTS', len(df), C['mid_blue'], ''),
        ('D', 'AT-RISK STUDENTS', int(df['is_at_risk'].sum()), C['red'], ''),
        ('F', 'CRITICAL RISK', int((df['risk_tier']=='Critical').sum()), 'C0392B', ''),
        ('H', 'AVG SEMESTER MARKS', f"{df['semester_marks'].mean():.1f}", C['green'], '/200'),
        ('J', 'AVG ATTENDANCE', f"{df['attendance'].mean():.1f}%", 'E67E22', ''),
        ('L', 'GRADE A STUDENTS', int((df['grade_label']=='A').sum()), '8E44AD', ''),
    ]
    for col, label, value, color, unit in kpis:
        ws.merge_cells(f'{col}6:{col}6')
        ws.merge_cells(f'{col}7:{col}7')
        ws.merge_cells(f'{col}8:{col}8')
        for r in range(6, 9):
            ws[f'{col}{r}'].fill = _fill('F8F9FA')
            ws.column_dimensions[col].width = 18
        ws[f'{col}6'].value     = label
        ws[f'{col}6'].font      = _font(bold=True, size=9, color='888888')
        ws[f'{col}6'].alignment = _align('center')
        ws[f'{col}7'].value     = str(value) + unit
        ws[f'{col}7'].font      = _font(bold=True, size=22, color=color)
        ws[f'{col}7'].alignment = _align('center')
        ws[f'{col}8'].fill      = _fill(color)
        ws.row_dimensions[8].height = 5

    # Risk distribution table
    ws['B10'] = 'RISK TIER BREAKDOWN'
    ws['B10'].font = _font(bold=True, size=12, color=C['dark_blue'])
    headers = ['Risk Tier', 'Count', 'Percentage', 'Action Required']
    actions = {
        'Low':      'No action needed — monitor regularly',
        'Moderate': 'Faculty advisory recommended',
        'High':     'Mandatory counselling & attendance review',
        'Critical': 'IMMEDIATE intervention required',
    }
    for c, h in enumerate(headers, 2):
        cell = ws.cell(row=11, column=c, value=h)
        cell.font      = _font(bold=True, color='FFFFFF')
        cell.fill      = _fill(C['dark_blue'])
        cell.alignment = _align('center')
        cell.border    = _border()

    row = 12
    for tier in ['Low', 'Moderate', 'High', 'Critical']:
        cnt = int((df['risk_tier'] == tier).sum())
        pct = cnt / len(df) * 100
        vals = [tier, cnt, f'{pct:.1f}%', actions[tier]]
        for c, v in enumerate(vals, 2):
            cell = ws.cell(row=row, column=c, value=v)
            cell.fill      = _fill(RISK_BG[tier])
            cell.alignment = _align('center' if c < 5 else 'left')
            cell.border    = _border()
            cell.font      = _font(size=10)
        row += 1

    ws.column_dimensions['B'].width = 16
    ws.column_dimensions['C'].width = 10
    ws.column_dimensions['D'].width = 14
    ws.column_dimensions['E'].width = 45

    # Grade distribution table
    ws['G10'] = 'GRADE BREAKDOWN'
    ws['G10'].font = _font(bold=True, size=12, color=C['dark_blue'])
    for c, h in enumerate(['Grade', 'Count', '%', 'Marks Range'], 7):
        cell = ws.cell(row=11, column=c, value=h)
        cell.font      = _font(bold=True, color='FFFFFF')
        cell.fill      = _fill(C['dark_blue'])
        cell.alignment = _align('center')
        cell.border    = _border()

    ranges = {'A': '165–200', 'B': '150–165', 'C': '135–150', 'D': '120–135', 'F': '<120'}
    row = 12
    for grade in ['A', 'B', 'C', 'D', 'F']:
        cnt = int((df['grade_label'] == grade).sum())
        pct = cnt / len(df) * 100
        for c, v in enumerate([grade, cnt, f'{pct:.1f}%', ranges[grade]], 7):
            cell = ws.cell(row=row, column=c, value=v)
            cell.fill      = _fill(GRADE_BG[grade])
            cell.alignment = _align('center')
            cell.border    = _border()
            cell.font      = _font(size=10, bold=(c == 7))
        row += 1

    ws.column_dimensions[get_column_letter(7)].width = 10
    ws.column_dimensions[get_column_letter(8)].width = 10
    ws.column_dimensions[get_column_letter(9)].width = 10
    ws.column_dimensions[get_column_letter(10)].width = 14


# ── Sheet 2: All Students ─────────────────────────────────────────────────────

def _build_all_students(ws, df):
    ws.sheet_properties.tabColor = C['mid_blue']
    headers = ['#', 'USN', 'Name', 'Attendance %', 'Internal', 'Assignment',
               'Quiz', 'Lab', 'Semester Marks', 'Study Hrs', 'Grade',
               'Risk Score', 'Risk Tier', 'Performance Index']
    col_widths = [5, 14, 20, 14, 11, 13, 8, 8, 16, 11, 9, 12, 13, 18]

    for c, (h, w) in enumerate(zip(headers, col_widths), 1):
        ws.column_dimensions[get_column_letter(c)].width = w
        cell = ws.cell(row=1, column=c, value=h)
        cell.font      = _font(bold=True, color='FFFFFF', size=10)
        cell.fill      = _fill(C['dark_blue'])
        cell.alignment = _align('center')
        cell.border    = _border()

    ws.row_dimensions[1].height = 22
    _freeze(ws, 'A2')

    display_cols = ['usn', 'name', 'attendance', 'internal_marks', 'assignment_score',
                    'quiz_score', 'lab_marks', 'semester_marks', 'study_hours',
                    'grade_label', 'risk_score', 'risk_tier', 'performance_index']
    df_sorted = df.sort_values('risk_score', ascending=False).reset_index(drop=True)

    for i, (_, row) in enumerate(df_sorted.iterrows(), 2):
        bg = RISK_BG.get(row['risk_tier'], C['white'])
        ws.cell(row=i, column=1, value=i-1).font = _font(size=9)

        for c, col in enumerate(display_cols, 2):
            val = row[col]
            if col in ('attendance', 'internal_marks', 'assignment_score',
                       'quiz_score', 'lab_marks', 'semester_marks',
                       'study_hours', 'risk_score', 'performance_index'):
                val = round(float(val), 2)
            cell = ws.cell(row=i, column=c, value=val)
            cell.fill      = _fill(bg if col == 'risk_tier' else C['white'])
            cell.alignment = _align('center' if c > 3 else 'left')
            cell.border    = _border('hair')
            cell.font      = _font(size=9)
            if col == 'grade_label':
                cell.fill = _fill(GRADE_BG.get(str(val), C['white']))
                cell.font = _font(size=9, bold=True)
            if col == 'risk_tier':
                cell.font = _font(size=9, bold=True,
                                  color=C[f'risk_{str(val).lower()}'] if f'risk_{str(val).lower()}' in C else '000000')

    # Conditional formatting: color scale on semester_marks (col 9)
    ws.conditional_formatting.add(
        f'I2:I{len(df)+1}',
        ColorScaleRule(start_type='min', start_color='E74C3C',
                       mid_type='percentile', mid_value=50, mid_color='F4D03F',
                       end_type='max', end_color='27AE60')
    )


# ── Sheet 3: At-Risk Students ─────────────────────────────────────────────────

def _build_at_risk(ws, df):
    ws.sheet_properties.tabColor = C['red']
    at_risk = df[df['is_at_risk'] == 1].sort_values('risk_score', ascending=False).reset_index(drop=True)

    ws.merge_cells('A1:N1')
    title = ws['A1']
    title.value     = f'⚠  AT-RISK STUDENTS — Requires Immediate Faculty Attention  ({len(at_risk)} students)'
    title.font      = _font(bold=True, size=12, color='FFFFFF')
    title.fill      = _fill(C['red'])
    title.alignment = _align('center')
    ws.row_dimensions[1].height = 25

    headers = ['#', 'USN', 'Name', 'Attendance%', 'Internal', 'Semester',
               'Study Hrs', 'Risk Score', 'Risk Tier', 'Grade',
               'Perf. Index', 'Primary Risk Factor', 'Recommended Action']
    col_widths = [5, 14, 22, 13, 11, 13, 11, 12, 13, 9, 13, 28, 40]

    for c, (h, w) in enumerate(zip(headers, col_widths), 1):
        ws.column_dimensions[get_column_letter(c)].width = w
        cell = ws.cell(row=2, column=c, value=h)
        cell.font      = _font(bold=True, color='FFFFFF', size=10)
        cell.fill      = _fill('8B0000')
        cell.alignment = _align('center')
        cell.border    = _border()

    _freeze(ws, 'A3')

    def _primary_risk(row):
        issues = []
        if row['attendance'] < 65:  issues.append(f"Low attendance ({row['attendance']:.1f}%)")
        if row['internal_marks'] < 25: issues.append(f"Low internals ({row['internal_marks']:.1f})")
        if row['semester_marks'] < 120: issues.append(f"Low semester marks")
        if row['study_hours'] < 2:  issues.append(f"Low study hours ({row['study_hours']:.1f}h)")
        return '; '.join(issues) if issues else 'Multiple factors'

    def _recommendation(row):
        if row['risk_tier'] == 'Critical':
            return 'URGENT: Contact student & guardian. Assign mentor. Review all assessments.'
        elif row['risk_tier'] == 'High':
            return 'Schedule counselling session. Monitor attendance weekly. Provide study resources.'
        return 'Advisory meeting recommended. Check assignment completion.'

    for i, (_, row) in enumerate(at_risk.iterrows(), 3):
        bg = RISK_BG.get(row['risk_tier'], C['white'])
        vals = [i-2, row['usn'], row['name'],
                round(row['attendance'], 1), round(row['internal_marks'], 1),
                round(row['semester_marks'], 1), round(row['study_hours'], 1),
                int(row['risk_score']), row['risk_tier'], row['grade_label'],
                round(row['performance_index'], 2),
                _primary_risk(row), _recommendation(row)]

        for c, v in enumerate(vals, 1):
            cell = ws.cell(row=i, column=c, value=v)
            cell.fill      = _fill(bg)
            cell.alignment = _align('center' if c not in (3, 12, 13) else 'left', wrap=(c >= 12))
            cell.border    = _border('hair')
            cell.font      = _font(size=9, bold=(c == 9))
        ws.row_dimensions[i].height = 30


# ── Sheet 4: ML Results ───────────────────────────────────────────────────────

def _build_ml_results(ws, reg_results, clf_results):
    ws.sheet_properties.tabColor = C['green']

    ws.merge_cells('A1:H1')
    ws['A1'].value     = 'Machine Learning Model Performance Summary'
    ws['A1'].font      = _font(bold=True, size=14, color='FFFFFF')
    ws['A1'].fill      = _fill(C['dark_blue'])
    ws['A1'].alignment = _align('center')

    # Regression
    ws['A3'] = 'REGRESSION MODELS — Predicting Semester Marks'
    ws['A3'].font = _font(bold=True, size=12, color=C['dark_blue'])
    for c, h in enumerate(['Model', 'RMSE', 'MAE', 'R² Score', 'Performance'], 1):
        cell = ws.cell(row=4, column=c, value=h)
        cell.font = _font(bold=True, color='FFFFFF')
        cell.fill = _fill(C['mid_blue'])
        cell.alignment = _align('center')
        cell.border = _border()
    ws.column_dimensions['A'].width = 22
    ws.column_dimensions['B'].width = 12
    ws.column_dimensions['C'].width = 12
    ws.column_dimensions['D'].width = 12
    ws.column_dimensions['E'].width = 20

    for i, (name, metrics) in enumerate(reg_results.items(), 5):
        perf = 'Excellent' if metrics['R2'] > 0.85 else ('Good' if metrics['R2'] > 0.70 else 'Fair')
        is_best = metrics['R2'] == max(m['R2'] for m in reg_results.values())
        bg = C['light_green'] if is_best else C['white']
        for c, v in enumerate([name + (' ★' if is_best else ''), metrics['RMSE'], metrics['MAE'], metrics['R2'], perf], 1):
            cell = ws.cell(row=i, column=c, value=v)
            cell.fill      = _fill(bg)
            cell.alignment = _align('center')
            cell.border    = _border('hair')
            cell.font      = _font(size=10, bold=is_best)

    # Classification
    start_row = 10
    ws.cell(row=start_row, column=1).value = 'CLASSIFICATION MODELS — Predicting Grade (A–F)'
    ws.cell(row=start_row, column=1).font  = _font(bold=True, size=12, color=C['dark_blue'])
    for c, h in enumerate(['Model', 'Accuracy', 'Performance'], 1):
        cell = ws.cell(row=start_row+1, column=c, value=h)
        cell.font = _font(bold=True, color='FFFFFF')
        cell.fill = _fill(C['mid_blue'])
        cell.alignment = _align('center')
        cell.border = _border()

    for i, (name, metrics) in enumerate(clf_results.items(), start_row+2):
        is_best = metrics['Accuracy'] == max(m['Accuracy'] for m in clf_results.values())
        bg = C['light_green'] if is_best else C['white']
        perf = 'Excellent' if metrics['Accuracy'] > 0.85 else ('Good' if metrics['Accuracy'] > 0.70 else 'Fair')
        for c, v in enumerate([name + (' ★' if is_best else ''), f"{metrics['Accuracy']*100:.1f}%", perf], 1):
            cell = ws.cell(row=i, column=c, value=v)
            cell.fill      = _fill(bg)
            cell.alignment = _align('center')
            cell.border    = _border('hair')
            cell.font      = _font(size=10, bold=is_best)


# ── Sheet 5: Statistics ───────────────────────────────────────────────────────

def _build_statistics(ws, df):
    ws.sheet_properties.tabColor = C['mid_blue']
    numeric_cols = ['attendance', 'internal_marks', 'assignment_score',
                    'quiz_score', 'lab_marks', 'semester_marks', 'study_hours']
    stats = df[numeric_cols].describe().round(3)

    ws.merge_cells('A1:I1')
    ws['A1'].value     = 'Descriptive Statistics — All Academic Features'
    ws['A1'].font      = _font(bold=True, size=13, color='FFFFFF')
    ws['A1'].fill      = _fill(C['dark_blue'])
    ws['A1'].alignment = _align('center')

    headers = ['Statistic'] + [c.replace('_', ' ').title() for c in numeric_cols]
    for c, h in enumerate(headers, 1):
        cell = ws.cell(row=2, column=c, value=h)
        cell.font = _font(bold=True, color='FFFFFF')
        cell.fill = _fill(C['mid_blue'])
        cell.alignment = _align('center')
        cell.border = _border()
        ws.column_dimensions[get_column_letter(c)].width = 18

    for r, (idx, row) in enumerate(stats.iterrows(), 3):
        bg = C['light_blue'] if r % 2 == 0 else C['white']
        ws.cell(row=r, column=1, value=idx).font = _font(bold=True, size=10)
        ws.cell(row=r, column=1).fill = _fill(C['header_row'])
        for c, v in enumerate(row.values, 2):
            cell = ws.cell(row=r, column=c, value=round(float(v), 3))
            cell.fill      = _fill(bg)
            cell.alignment = _align('center')
            cell.border    = _border('hair')
            cell.font      = _font(size=10)

    # Correlations
    start = len(stats) + 4
    ws.cell(row=start, column=1).value = 'Correlation with Semester Marks'
    ws.cell(row=start, column=1).font  = _font(bold=True, size=12, color=C['dark_blue'])
    corr = df[numeric_cols].corr()['semester_marks'].drop('semester_marks').round(4).sort_values(ascending=False)
    for c, (feat, val) in enumerate(corr.items(), 1):
        ws.cell(row=start+1, column=c).value = feat.replace('_', ' ').title()
        ws.cell(row=start+1, column=c).font  = _font(bold=True, color='FFFFFF')
        ws.cell(row=start+1, column=c).fill  = _fill(C['mid_blue'])
        ws.cell(row=start+1, column=c).alignment = _align('center')
        cell = ws.cell(row=start+2, column=c, value=float(val))
        cell.alignment = _align('center')
        bg = C['light_green'] if val > 0.3 else (C['light_red'] if val < 0 else C['light_yellow'])
        cell.fill = _fill(bg)
        cell.font = _font(size=10, bold=True)
        cell.border = _border('hair')


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_excel_report(df, reg_results, clf_results, output_path):
    wb = Workbook()
    wb.remove(wb.active)

    ws_dash  = wb.create_sheet('Dashboard')
    ws_all   = wb.create_sheet('All Students')
    ws_risk  = wb.create_sheet('At-Risk Students')
    ws_ml    = wb.create_sheet('ML Results')
    ws_stats = wb.create_sheet('Statistics')

    _build_dashboard(ws_dash, df)
    _build_all_students(ws_all, df)
    _build_at_risk(ws_risk, df)
    _build_ml_results(ws_ml, reg_results, clf_results)
    _build_statistics(ws_stats, df)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    wb.save(output_path)
    return output_path
