TEXTS = {
    "English": {
        # ── Login page ────────────────────────────────────────────────
        "title_text":           "Smart Campus Login",
        "login_subtitle":       "Please connect with your credentials",
        "login_portal_text":    "Faculty Portal",
        "student_portal_text":  "Student Portal",
        "faculty_tab":          "Faculty Login",
        "student_tab":          "Student Login",
        "student_usn_placeholder": "Enter your USN (e.g. 1RV21CSE1001)",
        "student_password_placeholder": "Enter your password (default: your USN)",
        "student_login_success": "Welcome back, student!",
        "student_usn_not_found": "❌ No student found with this USN",
        "student_invalid_password": "❌ Invalid password",
        "qr_login_text":        "QR Scan",
        "username_placeholder": "Enter username",
        "password_placeholder": "Enter password",
        "remember_text":        "Remember me",
        "login_button_text":    "Login",
        "login_success":        "Login successful!",
        "invalid_credentials":  "❌ Invalid username or password",
        "email_placeholder":    "Enter your registered email",
        "send_otp_text":        "Send OTP",
        "otp_success":          "OTP generated: {otp}",
        "verify_otp_text":      "Verify OTP",
        "otp_verified":         "✅ OTP Verified!",
        "invalid_otp":          "❌ Invalid OTP",
        "qr_scan_text":         "I have scanned the QR",
        "qr_verified":          "✅ QR Login Successful!",
        "forgot_password_text": "Forgot Password?",
        # ── Dashboard ─────────────────────────────────────────────────
        "main_title":      "Smart Campus Analytics",
        "subtitle":        "AI-Powered Early Risk Detection System",
        "hi_teacher":      "👋 Hi, Teacher",
        "logout":          "🚪 Logout",
        "nav_options":     ["Home", "Predictions", "Students", "Reports", "Year Comparison", "Settings"],
        "system_status":   "System Status",
        "total_students":  "Total Students",
        "at_risk":         "At-Risk",
        "on_track":        "On Track",
        "accuracy":        "Model Accuracy",
        # ── Filters ───────────────────────────────────────────────────
        "department":       "Department",
        "semester":         "Semester",
        "all_departments":  "All Departments",
        "all_semesters":    "All Semesters",
        # ── Student portal ────────────────────────────────────────────
        "welcome_student":      "Welcome",
        "your_attendance":      "Attendance",
        "your_internals":       "Internal Marks",
        "your_semester_marks":  "Semester Marks",
        "your_performance":     "Performance Index",
        "your_results":         "Results",
        "marks_breakdown":      "Marks Breakdown",
        "academic_profile":     "Academic Profile",
        "usn_label":            "USN",
        "name_label":           "Name",
        "department_label":     "Department",
        "semester_label":       "Semester",
        "footer":          "© 2026 Smart Campus Analytics · AI-Powered Early Risk Detection System",
    },
    "हिन्दी": {
        # ── Login page ────────────────────────────────────────────────
        "title_text":           "स्मार्ट कैंपस लॉगिन",
        "login_subtitle":       "कृपया अपने क्रेडेंशियल से कनेक्ट करें",
        "login_portal_text":    "शिक्षक पोर्टल",
        "student_portal_text":  "छात्र पोर्टल",
        "faculty_tab":          "शिक्षक लॉगिन",
        "student_tab":          "छात्र लॉगिन",
        "student_usn_placeholder": "अपना USN दर्ज करें (उदा. 1RV21CSE1001)",
        "student_password_placeholder": "अपना पासवर्ड दर्ज करें (डिफ़ॉल्ट: आपका USN)",
        "student_login_success": "वापस स्वागत है, छात्र!",
        "student_usn_not_found": "❌ इस USN वाला कोई छात्र नहीं मिला",
        "student_invalid_password": "❌ अमान्य पासवर्ड",
        "qr_login_text":        "QR स्कैन",
        "username_placeholder": "उपयोगकर्ता नाम दर्ज करें",
        "password_placeholder": "पासवर्ड दर्ज करें",
        "remember_text":        "मुझे याद रखें",
        "login_button_text":    "लॉगिन",
        "login_success":        "लॉगिन सफल!",
        "invalid_credentials":  "❌ अमान्य उपयोगकर्ता नाम या पासवर्ड",
        "email_placeholder":    "अपना पंजीकृत ईमेल दर्ज करें",
        "send_otp_text":        "OTP भेजें",
        "otp_success":          "OTP जनरेट हुआ: {otp}",
        "verify_otp_text":      "OTP सत्यापित करें",
        "otp_verified":         "✅ OTP सत्यापित!",
        "invalid_otp":          "❌ अमान्य OTP",
        "qr_scan_text":         "मैंने QR स्कैन कर लिया है",
        "qr_verified":          "✅ QR लॉगिन सफल!",
        "forgot_password_text": "पासवर्ड भूल गए?",
        # ── Dashboard ─────────────────────────────────────────────────
        "main_title":      "स्मार्ट कैंपस एनालिटिक्स",
        "subtitle":        "AI-संचालित प्रारंभिक जोखिम पहचान प्रणाली",
        "hi_teacher":      "👋 नमस्ते, शिक्षक",
        "logout":          "🚪 लॉगआउट",
        "nav_options":     ["होम", "भविष्यवाणी", "छात्र", "रिपोर्ट", "वर्ष तुलना", "सेटिंग्स"],
        "system_status":   "सिस्टम स्थिति",
        "total_students":  "कुल छात्र",
        "at_risk":         "जोखिम में",
        "on_track":        "सही रास्ते पर",
        "accuracy":        "मॉडल सटीकता",
        # ── Filters ───────────────────────────────────────────────────
        "department":       "विभाग",
        "semester":         "सेमेस्टर",
        "all_departments":  "सभी विभाग",
        "all_semesters":    "सभी सेमेस्टर",
        # ── Student portal ────────────────────────────────────────────
        "welcome_student":      "स्वागत है",
        "your_attendance":      "उपस्थिति",
        "your_internals":       "आंतरिक अंक",
        "your_semester_marks":  "सेमेस्टर अंक",
        "your_performance":     "प्रदर्शन सूचकांक",
        "your_results":         "परिणाम",
        "marks_breakdown":      "अंकों का विवरण",
        "academic_profile":     "शैक्षणिक प्रोफ़ाइल",
        "usn_label":            "USN",
        "name_label":           "नाम",
        "department_label":     "विभाग",
        "semester_label":       "सेमेस्टर",
        "footer":          "© 2026 स्मार्ट कैंपस एनालिटिक्स · AI-संचालित प्रारंभिक जोखिम पहचान प्रणाली",
    },
    "ಕನ್ನಡ": {
        # ── Login page ────────────────────────────────────────────────
        "title_text":           "ಸ್ಮಾರ್ಟ್ ಕ್ಯಾಂಪಸ್ ಲಾಗಿನ್",
        "login_subtitle":       "ದಯವಿಟ್ಟು ನಿಮ್ಮ ರುಜುವಾತುಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ",
        "login_portal_text":    "ಶಿಕ್ಷಕರ ಪೋರ್ಟಲ್",
        "student_portal_text":  "ವಿದ್ಯಾರ್ಥಿ ಪೋರ್ಟಲ್",
        "faculty_tab":          "ಶಿಕ್ಷಕರ ಲಾಗಿನ್",
        "student_tab":          "ವಿದ್ಯಾರ್ಥಿ ಲಾಗಿನ್",
        "student_usn_placeholder": "ನಿಮ್ಮ USN ನಮೂದಿಸಿ (ಉದಾ. 1RV21CSE1001)",
        "student_password_placeholder": "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ (ಡೀಫಾಲ್ಟ್: ನಿಮ್ಮ USN)",
        "student_login_success": "ಮರಳಿ ಸ್ವಾಗತ, ವಿದ್ಯಾರ್ಥಿ!",
        "student_usn_not_found": "❌ ಈ USN ನೊಂದಿಗೆ ಯಾವ ವಿದ್ಯಾರ್ಥಿಯೂ ಕಂಡುಬಂದಿಲ್ಲ",
        "student_invalid_password": "❌ ಅಮಾನ್ಯ ಪಾಸ್‌ವರ್ಡ್",
        "qr_login_text":        "QR ಸ್ಕ್ಯಾನ್",
        "username_placeholder": "ಬಳಕೆದಾರ ಹೆಸರು ನಮೂದಿಸಿ",
        "password_placeholder": "ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
        "remember_text":        "ನನ್ನನ್ನು ನೆನಪಿಡಿ",
        "login_button_text":    "ಲಾಗಿನ್",
        "login_success":        "ಲಾಗಿನ್ ಯಶಸ್ವಿ!",
        "invalid_credentials":  "❌ ಅಮಾನ್ಯ ಬಳಕೆದಾರ ಹೆಸರು ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್",
        "email_placeholder":    "ನಿಮ್ಮ ನೋಂದಾಯಿತ ಇಮೇಲ್ ನಮೂದಿಸಿ",
        "send_otp_text":        "OTP ಕಳುಹಿಸಿ",
        "otp_success":          "OTP ರಚಿಸಲಾಗಿದೆ: {otp}",
        "verify_otp_text":      "OTP ಪರಿಶೀಲಿಸಿ",
        "otp_verified":         "✅ OTP ಪರಿಶೀಲಿಸಲಾಗಿದೆ!",
        "invalid_otp":          "❌ ಅಮಾನ್ಯ OTP",
        "qr_scan_text":         "ನಾನು QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ್ದೇನೆ",
        "qr_verified":          "✅ QR ಲಾಗಿನ್ ಯಶಸ್ವಿ!",
        "forgot_password_text": "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?",
        # ── Dashboard ─────────────────────────────────────────────────
        "main_title":      "ಸ್ಮಾರ್ಟ್ ಕ್ಯಾಂಪಸ್ ಅನಾಲಿಟಿಕ್ಸ್",
        "subtitle":        "AI-ಚಾಲಿತ ಆರಂಭಿಕ ಅಪಾಯ ಪತ್ತೆ ವ್ಯವಸ್ಥೆ",
        "hi_teacher":      "👋 ನಮಸ್ಕಾರ, ಶಿಕ್ಷಕರೇ",
        "logout":          "🚪 ಲಾಗ್‌ಔಟ್",
        "nav_options":     ["ಹೋಮ್", "ಮುನ್ಸೂಚನೆ", "ವಿದ್ಯಾರ್ಥಿಗಳು", "ವರದಿಗಳು", "ವರ್ಷ ಹೋಲಿಕೆ", "ಸೆಟ್ಟಿಂಗ್ಸ್"],
        "system_status":   "ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ",
        "total_students":  "ಒಟ್ಟು ವಿದ್ಯಾರ್ಥಿಗಳು",
        "at_risk":         "ಅಪಾಯದಲ್ಲಿ",
        "on_track":        "ಸರಿಯಾದ ಹಾದಿಯಲ್ಲಿ",
        "accuracy":        "ಮಾಡೆಲ್ ನಿಖರತೆ",
        # ── Filters ───────────────────────────────────────────────────
        "department":       "ವಿಭಾಗ",
        "semester":         "ಸೆಮಿಸ್ಟರ್",
        "all_departments":  "ಎಲ್ಲಾ ವಿಭಾಗಗಳು",
        "all_semesters":    "ಎಲ್ಲಾ ಸೆಮಿಸ್ಟರ್",
        "footer":          "© 2026 ಸ್ಮಾರ್ಟ್ ಕ್ಯಾಂಪಸ್ ಅನಾಲಿಟಿಕ್ಸ್ · AI-ಚಾಲಿತ ಆರಂಭಿಕ ಅಪಾಯ ಪತ್ತೆ ವ್ಯವಸ್ಥೆ",
    },
}
