[server]
headless = true
port = 8501
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0075FF"
backgroundColor = "#020515"
secondaryBackgroundColor = "#0a0e23"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"
